### ISSUE TITLE
Tech Jam Virtual Reality Experience

### ISSUE THREAD

**Issue by DACole** [CityOfBoston/av-club#1]
Example description

[Here's a link to nowhere](https://www.google.com)
![example image](https://cloud.githubusercontent.com/assets/25957670/26074153/c6dc0a66-397e-11e7-9874-f4ba8990dea9.png)

**Comment by SarahFigalora** [comment]
This project is in coordination with DoIT's table at TechJam on June 15, it will be a VR experience through City Hall. The journey will start exactly where our TechJam table is for an extra crazy VR experience.
