### ISSUE TITLE
A Day with the Parks - Tree Crew

### ISSUE THREAD

**Issue by KristopherCarter** [CityOfBoston/av-club#15]
beefy dudes with chainsaws - Parks would like to produce a story on there tree team.

**Comment by DACole** [comment]
any thoughts on a deadline...GH4 over crank sounds like it could be cool.

**Comment by KristopherCarter** [comment]
Probably a mid-summer project, we tend to get a lot of tree calls during hurricane season if we have one this year. So that would mean a release in late September. GH4 overcrank and head/chest-mounted go-pros with people cutting down trees would be good visuals. We should see if they do plantings too, timelapse of a set of trees installed might be good to.

**Comment by KristopherCarter** [comment]
Post-poned until spring - but very helpful in spring with a focus on tree care for community partners
