### ISSUE TITLE
A story about Don Harney on film. 

### ISSUE THREAD

**Issue by DACole** [CityOfBoston/av-club#16]
If I get the bolex in July, I was thinking about asking Don, if can he tell us a story about documenting the mayor on actual film. I believe Isabel was also documenting on film as well and they would use the dark room on floor one which has since be removed. She is out with a broken knee, but maybe just filming a short interview and some cool shots of him with one of his hassleblads taking a photo of the mayor could be a cool side piece. I think there was also a process moving all the physical negatives to archival and how they now work with digital files on a large server.

History + Technology + Data Management + Archival + 16mm = nice little short story

**Comment by KristopherCarter** [comment]
That could be really interesting. I'd love to get Don's personal story - who mentored him, etc.

**Comment by DACole** [comment]
Yeah, I have heard a lot of stories about him working for the newspaper in Chelsea and also how it was working alongside other local greats like: **Stanley Joseph Forman**  an American former photojournalist who won a Pulitzer Prize two years in a row while working at the Boston Herald American. 

He has also told me about wearing a freezer suit because it had many pockets and allowed him to carry the bulky flash kits of the past maybe he still has the jacket at home somewhere.

**Comment by DACole** [comment]
I asked Don and he said he is totally up for it and can provide lots of old negatives and tools of the past.

**Comment by DACole** [comment]
Waiting to see if I will get access to a bolex. MassArt is suppose to provide this....

**Comment by DACole** [comment]
I need to check in with Patricia about this project. Will craft a better storyboard to present to her.

**Comment by DACole** [comment]
This is going to be closed...as there is no need for this type of content at the moment.
