### ISSUE TITLE
Imagine Boston

### ISSUE THREAD

**Issue by amateurmenace** [CityOfBoston/av-club#18]

**Comment by DACole** [comment]
StoryLab: consisted of a video booth, Love Letters to Boston, Expansion VR, Documentation VR, Post Cards and dialogue between Monum and constituent. Timelapse photography and video documentation was also used inside the old american bank building. The goal being to capture the emotions and stories of the constituent as they gather around the days activities at the launch of IB2030.

**Comment by DACole** [comment]
We plan to have four VR headsets one for each location. We also discussed audio boxes that could capture the stories as well. These would be setup at a number of locations throughout the exhibit allowing people to speak freely about the event and launch. This was eventually thrown out.

**Comment by DACole** [comment]
Process of preparation was smooth, meetings with Sabrina, IB2030, and Stephen Walter went according to plan.

**Comment by DACole** [comment]
Day of production, we traveled with many mobile devices to the location, spent time setting up and providing context for individuals to be apart of the experience.

**Comment by DACole** [comment]
content has began backup process. still waiting for direction on how to edit and share content or will it be used for archival purposes.
