### ISSUE TITLE
HQ2 Testimonials

### ISSUE THREAD

**Issue by KristopherCarter** [CityOfBoston/av-club#32]
Five interviews with people for HQ2 to be completed by 10/15. Awaiting Crystal Torman on list and schedule

**Comment by DACole** [comment]
Ann Klee: Filmed, draft edit, footage in cloud
MJW:Filmed, draft edit, footage in cloud
Zorica Pantić: Filmed, draft edit, footage in cloud

**Comment by DACole** [comment]
Final interviews to be filmed tomorrow at 2pm. From there edits will be made.

**Comment by DACole** [comment]
President of BU,Filmed, draft edit, footage in cloud
VP of Berklee,Filmed, draft edit, footage in cloud
Student of Northeastern,Filmed, draft edit, footage in cloud
 
Also posted edits of first round of q & a

**Comment by DACole** [comment]
Filmed last Q&A's today,  draft edit, footage in cloud

**Comment by DACole** [comment]
All videos live on the website. Their may be minor design changes made over the next week.
