### ISSUE TITLE
Video : CoB Re-brand explainer

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/av-club#34]
@daren: The CoB needs a video to explain the how its brand works and its origins. 
Due Date: Fri, December 22
Example below:
https://www.youtube.com/watch?v=xKu2de0yCJI 

Video should talk about
- Brand logic
- COLOR
- LOGO AND SEALS
- TYPOGRAPHY
- ICONOGRAPHY
- PHOTOGRAPHY
- TOOLKIT

**Comment by DACole** [comment]
I spent some time organizing some thoughts around the layout of the project. I am curious about the V/O at this point...and if I should just follow the language that is posted on the brand guideline page, as it is written pretty well already?

Besides that I plan to start pulling the samples to make the edit at the start of next week...

I watch the youtube link as well...and think that is a really good format to follow.

**Comment by DACole** [comment]
Submitted a draft edit, will meet with Sebastian about edits.

**Comment by sebastianebarb** [comment]
@DACole notes for first draft are here, please take a look.

 https://docs.google.com/a/boston.gov/document/d/1u1EjKEWKvav3X2GUzNowOvis4HrshVC6G1RKwCucrVg/edit?usp=sharing

**Comment by DACole** [comment]
Thanks for the notes...
will edit and send these back this week...most likely before the end of the week.

**Comment by DACole** [comment]
Turned in a second draft...new list of changes...adding in Laura Melle to do a new Voice Over.
making changes and edits now.

**Comment by sebastianebarb** [comment]
@DACole will have next draft by the end of the day Thursday Jan 18. (note added Tuesday Jan 16)

Overview:
- Please make all titles uppercase and put them in the same place each time.
- Section Titles - Section title sizing (e.g. Color Relationships, Typography, and Photography) is inconsistent.
- We need to add a header slide for the video. Even if it's quick, something along the lines of 'City of Boston Branding Guide' would be helpful to let viewers know what they're getting into
- Transitions between section seem quick (example color to logo ~ 0:35)
- The phrase where Laura says 'we are human' sounds a little robotic/can it sound more human?
- Titles are a combo of one line and two line, standardizing them at the top should alow them to be on one line.
Detailed notes:
0:35: 
0:49: Make sure the tiles is the same point size as other titles. 
0:53: Please add the following lines to Type section. "Montserrat is used for headlines in capital letters and Lora should be used for large blocks of text. both are available on the online brand guidelines."
0:53: Reduce all content on icon page by 20% and re-space.
0:53: Make lines and text a medium gray to have the icons pop more.
1:09: Chance small round icons to say "Small circular icons are used to show activities at parks, community centers and other city locations. 
Experiential example > is there a less controversial example we could use than 'paying a parking ticket'?
1:14: The word department seams like it is not aligned correctly. and it shift when the next icon title comes on screen.
1:17: Downloaded content at the bottom of the screen.
1:26: Make sure the tiles is the same point size as other titles.
1:31: Timing speeds up greatly all of a sudden. Have photos rove across time.
1:37: Remove David B pumpkins and honey apple B graphics 
1:40: B needs to be better aligned with the previous graphic. It looks like it shifts.
1:43: have the made by lock up on screen for another second.  make the text Laura
1:46: Have the text set with no capitals set in Laura. Remove www.

**Comment by DACole** [comment]
New Voice over:

"The new mark for Boston is the bold letter B, underlined. The B is a way to strike a friendly tone. While the seal is a symbol of authority, the B and the longer City of Boston logo is our way of showing we are human."

"Montserrat is used for headlines in capital letters and Lora should be used for large blocks of text. both are available on the online brand guidelines."

**Comment by DACole** [comment]
Turned in version 4 of the video brand explainer.
https://drive.google.com/file/d/1GPsxLCTjiWBEdDmcR911B1RjUPqSeemS/view?usp=sharing

awaiting feedback.

**Comment by sebastianebarb** [comment]
Notes:
1:10: text "experiential" is not centred on the icon.
1:18: Missing new voice over "Small circular icons are used to show activities at parks, community centres and other city locations"

**Comment by DACole** [comment]
Laura and I will record the new voice over today and I can fix the alignment. 

We recorded the voice over...will make edits and resubmit.

**Comment by DACole** [comment]
Resubmitted the updated changes to voice over and text alignment. Let me know if you need anything else. 

https://drive.google.com/open?id=10tAoX1RJ7IspjyeyYV2aRnBgJzsCEu6F
