### ISSUE TITLE
Environment Storytelling

### ISSUE THREAD

**Issue by DACole** [CityOfBoston/av-club#41]
from Mugzy....
I wanted to reach out to you because we were thinking it would be awesome to put together a video with all of our new Climate Ready Boston Leaders and their work. Over the next few months, each of the leaders will be hosting events and presenting Climate Ready Boston materials. I will be attending most of them and thought if I captured some footage then at the end we could put together an interesting short video that tells the story of our collaborative work. 

We have a meeting setup to learn more.

**Comment by sebastianebarb** [comment]
@DACole this is fine as long as she is shooing the video.
