### ISSUE TITLE
Blog post: video brand guidelines

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/av-club#45]
Darren and Sebastian,

Please write a blog post about the video brand guidelines.

**Comment by DACole** [comment]
Will Review, to see everyone is happy with post. Should be finished.

**Comment by DACole** [comment]
https://docs.google.com/document/d/1juSsI3xPM6RQ9p3ldD3AJsy9L2yVqPlFTuY2-pUd4VI/edit?usp=sharing
