### ISSUE TITLE
Captions and Subtitles Explored

### ISSUE THREAD

**Issue by DACole** [CityOfBoston/av-club#46]
Summary:
Carving out time to develop a better approach of including more languages to the creative content we are releasing. Also looking at automated tools that can better help us resolve issues when dealing with multiple languages.

**Comment by DACole** [comment]
I spoke with Reilly and she mentioned we can access her notes once we have our information together about translations and subtitles.

**Comment by DACole** [comment]
I will start pulling a list of resources and articles that are speaking about how to deal with the issue of translation and having a wider voice when making content for cities. I also think this could be a research area we could get funding in to help us pay for things. 

[GOOGLE DOC FOR LINKS](https://docs.google.com/document/d/18lgG0vdfEDAmyWs1Vjc1TZL6Zi9R3RB6nFL324BzepA/edit?usp=sharing)

**Comment by DACole** [comment]
There is a webinar coming up that we will listen to and figure out what the leaders in captioning are doing to lower the cost

**Comment by DACole** [comment]
We watch part of the IBM Watson Webinar that had a lot to speak about their new improvements to captioning, we want to reach out to them about how to better think through translations if the dialogue is in English what is the most affordable and accurate way to have them translated in the many other languages that are needed for communities within the city.

**Comment by sebastianebarb** [comment]
![Hunting Cat Wallpapers 1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46c08194378b8daecfcabe57e46af198255626632c16b06b21c7af6aaf50740b0a0c0abe4b4a5a4dfdf0df7aa5e03475880903b9d16e5725c03445a9be840da313f871d51bdaebe5c01982fa3737e68c854e3b1c07188efd553da19c48c14abb.jpg)
