### ISSUE TITLE
Thersa India Young: Artist video

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/av-club#61]
Contact: John.crowley@boston.gov
Date due: 

- [x] Film Shoot
- [x] Edting
- [x] Shiped

**Comment by DACole** [comment]
This has been filmed, and uploaded to the internet, but the using a powered speaker for the microphone, that can also allow for a master mix to be pulled from for the audio track of the video that is documented.

**Comment by DACole** [comment]
https://drive.google.com/open?id=1Z-6S0uw4H2MwNYjUMtqnB5YqhdkCyZM5

better mic hookup would make this a better audio experience. Currently the microphone was just a lav mic between all of the panel members, there is also a very loud vent in the space.
