### ISSUE TITLE
Who Picks Up Your Trash video

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/av-club#64]
Contact: lauren.zingarelli@boston.gov
Deadline:

Notes:
The environment would like a video to talk about how to deal with trash. More notes inbound.

**Comment by DACole** [comment]
"our perspective is to model the right practices of recycling and to demonstrate that collective action moves us closer to our climate goals while creating a healthier environment."

**Comment by DACole** [comment]
Updated proposals provided by Robbie
https://docs.google.com/document/d/1HMAz8DDI5jDX4x1tWR_l_FVmG0ENrkkeGTaZMSZzdhY/edit?usp=sharing

**Comment by DACole** [comment]
Sent an update email to Lauren to see if they still want to run this project...

**Comment by DACole** [comment]
I am going to close this since Robbie is no longer here and Lauren just started me on a new project, they can resubmit for this project if they want to bring it to life.
