### ISSUE TITLE
Net Neutrality 

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/av-club#8]

**Comment by SarahFigalora** [comment]
Video project pitched by Anne Schweiger, would coordinate with a Net Neutrality Town Hall. Still waiting approval to move forward.

**Comment by DACole** [comment]
The video was launched on the day of action and received a good response, from the public. It was also embedded GovTech with a larger story on the Net Neutrality. 

Digital team helped and provided illustrations.
